version: '3.7'
services:
  web:
    build: .
    container_name: flask-app3-demo
    restart: unless-stopped
    command: /bin/sh -c 'flask run --host=0.0.0.0 --port=9003'
    ports:
      - 9003:9003
    volumes:
      - .:/src
    environment:
      FLASK_ENV: development
      VIRTUAL_HOST: app3.example.com
      VIRTUAL_PORT: 9003
    network_mode: bridge
    external_links:
      - mysql
